name: astro_mvp
description: A calm, personal astrology MVP.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  fl_chart: '>=0.70.2 <2.0.0'
  flutter_animate: ^4.5.2
  google_fonts: '>=6.2.1 <7.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/gender_couple.png
